### ISSUE TITLE
No recording created

### ISSUE THREAD

**Issue by nstickney** [b12f/wlstreamer#9]
Installed from AUR, kernel 5.10.11-arch1-1. `wf-recorder` works correctly.

```
$ wlstreamer --verbose
...
Choosing pixel format yuyv422
Output #0, video4linux2,v4l2, to '/dev/video0':
    Stream #0:0: Unknown: none (rawvideo)
[video4linux2,v4l2 @ 0x7f6b1c000d00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[video4linux2,v4l2 @ 0x7f6b1c000d00] ioctl(VIDIOC_G_FMT): Invalid argument
Failed to write file header
Invalid argument
...
```

**Comment by b12f** [comment]
Hi @nstickney and sorry for the late response. Are you sure `/dev/video0` is available?

**Comment by nstickney** [comment]
No worries; thank you for the response!

I don't know that I understand your question; perhaps I am using it wrong. `/dev/video0` exists, if that's what you mean.

```
$ ls /dev/video*
/dev/video0  /dev/video1  /dev/video2
```

Should I be passing arguments? Should I be using `wlstreamer` in conjunction with another program?

**Comment by b12f** [comment]
I'm not sure what your usecase is, but I've created this program to enable users to share multiple screens in wayland. wlstreamer does this by taking wf-recorder streams, and merging them in one `v4l2loopback` output, which would be one of the `/dev/video` devices. `wlstreamer --help` gives more information on this, especially regarding having multiple different resolutions in place.

The ability to record to a file was pretty much dropped once multiple resolutions came in, since `v4l2loopback` was a hard dependency at that point anyway. Recording is still possible by e.g. taking the output from `/dev/video$n` and saving that to a file, for example with vlc or obs.

**Comment by b12f** [comment]
For example, I have three monitors, all with the same resolution.

```
wlstreamer --not-screen DP-3 --not-ws 8 --not-ws 9 --not-ws 4 --not-ws 5 -d 2
```
This uses `/dev/video2` as the output device, and hides one of my screens, as well as workspace number 8, 9, 4 and 5.

You can then open e.g. meet.jit.si and select the loopback device as your webcam.

**Comment by nstickney** [comment]
Ah! I had found the project in some way that declared `wlstreamer` to be somehow related to `wf-recorder`; I didn't understand how it worked. Thanks for your reply. I suppose from your response that I need to pick a video device that is not already in `/dev/video*`?

**Comment by b12f** [comment]
You'd need to create `/dev/video` loopback devices. The kernel module `v4l2loopback` does this for you. Then you use one of those as your output device, and you can select it in e.g. firefox or chrome as your webcam.

**Comment by nstickney** [comment]
So, when I `modprobe v4l2loopback`, I see that another video device is created: `\dev\video2`. I run `wlstreamer -d 2` to use that device... and then I can use "Dummy video device" in Discord, etc. Thanks! Is there a good way to use this with `wf-recorder` to record?

**Comment by b12f** [comment]
If you'd want to record, I'd recommend a program that takes `/dev/video2` and then writes that stream to a file. `vlc`, `obs-studio`, `ffmpeg` and others are candidates here, it depends a bit on your needs. Googling something like "Record webcam to file" should suffice here, since what `/dev/video2` provides is a video stream in common webcam settings.

**Comment by nstickney** [comment]
I understand and have that much working, thanks!
